//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCartApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Description { get; set; }
        public decimal Product_Price { get; set; }
        public string Product_Image_Path { get; set; }
        public Nullable<int> Product_Category_Id { get; set; }
    
        public virtual Product_Category Product_Category { get; set; }
    }
}
